<div id="review-section" class="review-section hidden">
    <h2>Check your Work</h2>
    <p>
        On test day, you won't be able to move on to the next module until time expires. <br>
        For these practice questions, you can click <strong>Next</strong> when you're ready to move on.
    </p>

    <!-- Question Navigation Box -->
    <div class="question-navigation-box">
        <div class="text-center mb-4">
            <h4>{{ $sectionTitle ?? 'Section Questions' }}</h4>
        </div>
        <div class="question-nav-row flex text-center">
            <div class="flex-1 flex items-center justify-center gap-2">
                <svg fill="#000000" version="1.1" xmlns="http://www.w3.org/2000/svg" width="16px" height="16px"
                    viewBox="0 0 389 389">
                    <g>
                        <g>
                            <g>
                                <path
                                    d="M379,326.035h-18.852c-5.522,0-10,4.477-10,10v14.111h-14.113c-5.522,0-10,4.477-10,10V379c0,5.523,4.478,10,10,10H379c5.522,0,10-4.477,10-10v-42.965C389,330.512,384.522,326.035,379,326.035z" />
                                <path
                                    d="M166.927,350.146h-58.813c-5.522,0-10,4.477-10,10V379c0,5.523,4.478,10,10,10h58.813c5.522,0,10-4.477,10-10v-18.854C176.927,354.623,172.449,350.146,166.927,350.146z" />
                                <path
                                    d="M280.887,350.146h-58.812c-5.523,0-10,4.477-10,10V379c0,5.523,4.477,10,10,10h58.812c5.522,0,10-4.477,10-10v-18.854C290.887,354.623,286.409,350.146,280.887,350.146z" />
                                <path
                                    d="M52.965,350.146H38.852v-14.111c0-5.523-4.478-10-10-10H10c-5.522,0-10,4.477-10,10V379c0,5.523,4.478,10,10,10h42.965c5.521,0,10-4.477,10-10v-18.854C62.965,354.623,58.486,350.146,52.965,350.146z" />
                                <path
                                    d="M10,290.886h18.852c5.522,0,10-4.477,10-10v-58.812c0-5.523-4.478-10-10-10H10c-5.522,0-10,4.477-10,10v58.812C0,286.409,4.478,290.886,10,290.886z" />
                                <path
                                    d="M10,176.926h18.852c5.522,0,10-4.477,10-10v-58.812c0-5.523-4.478-10-10-10H10c-5.522,0-10,4.477-10,10v58.812C0,172.449,4.478,176.926,10,176.926z" />
                                <path
                                    d="M52.965,0H10C4.478,0,0,4.477,0,10v42.967c0,5.523,4.478,10,10,10h18.852c5.522,0,10-4.477,10-10V38.854h14.113c5.521,0,10-4.477,10-10V10C62.965,4.478,58.486,0,52.965,0z" />
                                <path
                                    d="M280.887,0h-58.812c-5.522,0-10,4.477-10,10v18.854c0,5.523,4.478,10,10,10h58.812c5.522,0,10-4.477,10-10V10C290.887,4.478,286.409,0,280.887,0z" />
                                <path
                                    d="M108.113,38.854h58.813c5.522,0,10-4.477,10-10V10c0-5.523-4.478-10-10-10h-58.813c-5.522,0-10,4.477-10,10v18.854C98.113,34.377,102.591,38.854,108.113,38.854z" />
                                <path
                                    d="M379,0h-42.965c-5.522,0-10,4.477-10,10v18.854c0,5.523,4.478,10,10,10h14.113v14.113c0,5.523,4.478,10,10,10H379c5.522,0,10-4.477,10-10V10C389,4.478,384.522,0,379,0z" />
                                <path
                                    d="M379,212.074h-18.852c-5.522,0-10,4.477-10,10v58.812c0,5.522,4.478,10,10,10H379c5.522,0,10-4.478,10-10v-58.812C389,216.551,384.522,212.074,379,212.074z" />
                                <path
                                    d="M379,98.114h-18.852c-5.522,0-10,4.477-10,10v58.812c0,5.523,4.478,10,10,10H379c5.522,0,10-4.477,10-10v-58.812C389,102.591,384.522,98.114,379,98.114z" />
                            </g>
                        </g>
                    </g>
                </svg>
                <span>Unanswered</span>
            </div>
            <div class="flex-1 flex items-center justify-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="#ab2334"
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                    class="feather feather-bookmark">
                    <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"></path>
                </svg>
                <span>For Review</span>
            </div>
            <div class="flex-1 flex items-center justify-center gap-2">
                <div style="width: 18px; height: 18px; background-color: #324dc7;"></div>
                <span>Answered</span>
            </div>
        </div>
        <div class="flex flex-wrap gap-4 justify-start py-4" style="min-height: 100px;">
            <!-- Question buttons will be dynamically generated by JavaScript -->
        </div>
    </div>
</div>
